//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gibdd
{
    using System;
    using System.Collections.Generic;
    
    public partial class Licences
    {
        public int IdZapis { get; set; }
        public int idDriver { get; set; }
        public System.DateTime LicenceDate { get; set; }
        public System.DateTime ExpireDate { get; set; }
        public string Categories { get; set; }
        public string LicenceSeries { get; set; }
        public string LicenceNumber { get; set; }
        public string Issued { get; set; }
        public string City { get; set; }
    
        public virtual Drivers Drivers { get; set; }
    }
}
